### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: NYU JCA
email: nyu.jca@gmail.com
description: The official website of NYU JCA
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#c0ffee'
twitter_username: 
github_username:  uetuluk
author: Utku Ege Tuluk
logo: assets/images/large-logo.png
twitter:
  username: 
social:
  name: Utku Ege Tuluk
  links:
    - https://github.com/uetuluk

languages: ["en", "ja"]
ampdir: amp
netlify_cms: true

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
# webmaster_verifications:
#  google: verification_code
google_analytics: UA-150440868-1
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
